services:
  - type: web
    name: skb-tryout
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: "SKB Tryout"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: "base64:kyV2/HVQilQdU7HT5c9xBsUVo+35tDug0Wc6ySoZRQo="
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: sqlite
      - key: APP_SEED
        value: "true"
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
